import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {mkdir} from 'node:fs/promises';
import {kvScenario,encode,decode,base62} from '../src/models.js';
assert.equal(kvScenario(1,2,true,-1,'C').find(x=>'value'in x).value,1);
assert.equal(kvScenario(2,2,true,-1,'C').find(x=>'value'in x).value,2);
assert.equal(kvScenario(3,3,true,2,'C').find(x=>'value'in x).value,null);
assert.equal(base62(11157),'2TX');
assert.deepEqual(decode(encode(2199023255551,31,31,4095)),[2199023255551,31,31,4095]);
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173/system-design-learning-lab/',{waitUntil:'networkidle'});
const visible=()=>page.locator('main > div:not([hidden])');
await visible().getByRole('button',{name:'下一步 →',exact:true}).click();
assert.match(await visible().locator('.event').innerText(),/A 写入/);
await visible().getByRole('button',{name:'隔离并同时写入'}).click();
await visible().getByRole('button',{name:'恢复网络并处理'}).click();
assert.match(await visible().locator('#kv-conflict .result').innerText(),/书 \+ 笔/);
await page.getByRole('navigation',{name:'章节',exact:true}).getByRole('button').nth(1).click();
await visible().getByRole('button',{name:'生成 4097 个',exact:true}).click();
assert.match(await visible().locator('#id-main .result').innerText(),/4096 个，1 个等待/);
await visible().getByRole('button',{name:'时钟 -5 ms'}).click();
await visible().getByRole('button',{name:'生成 1 个',exact:true}).click();
assert.match(await visible().locator('#id-main .result').innerText(),/回拨 5 ms/);
await page.getByRole('navigation',{name:'章节',exact:true}).getByRole('button').nth(2).click();
await visible().getByRole('button',{name:'准备碰撞场景'}).click();
await visible().getByRole('button',{name:'强制候选 ab'}).click();
assert.equal(await visible().locator('#url-main tbody tr').count(),2);
assert.match(await visible().locator('#url-main tbody tr').first().innerText(),/original/);
await visible().getByLabel('响应与浏览器缓存预设').selectOption('301');
await visible().getByRole('button',{name:'模拟点击 →'}).click();
await visible().getByRole('button',{name:'模拟点击 →'}).click();
assert.deepEqual(await visible().locator('.metrics strong').allTextContents(),['2','1','1']);
await visible().getByLabel('我的判断、实验的证据、修正后的原则').fill('浏览器缓存能绕过服务。');
await page.reload({waitUntil:'networkidle'});
assert.equal(await visible().getByLabel('我的判断、实验的证据、修正后的原则').inputValue(),'浏览器缓存能绕过服务。');
await page.getByRole('navigation',{name:'章节',exact:true}).getByRole('button').first().click();
await page.evaluate(()=>window.scrollTo(0,0));await page.evaluate(()=>document.fonts.ready);
await mkdir('assets',{recursive:true});await page.screenshot({path:'assets/screenshot.png'});
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'assets/mobile.png',fullPage:false});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: quorum, 64-bit roundtrip, collision preservation, overflow, rollback, cache accounting, notes, mobile width, no runtime errors.');
